# Site settings
title: Kimyeongmin Portfolio
description: A blog about Kim Yeong-Min
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 김영민
user_description: 


user_title: Software, A.I Developer
email: zkdhtmthfwu9@naver.com
github_username:  wkdoekofekfoekf


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
